### ISSUE TITLE
Support workspaces

### ISSUE THREAD

**Issue by qryxip** [tanakh/cargo-atcoder#35]
#18 で言った「多数のパッケージを一つのワークスペースで管理することでwarmupを不要にする」という話です。

Rustのワークスペースは同名の`bin`を含むことは非推奨で`cargo`コマンドの度にwarningが出ます。 無視するにしてもrust-analyzer等のツールが将来にわたって動いてくれるとは限りません。 ゆえに`bin`のリネームが必要だと考えます。

`bin`をリネームするにあたって`problem-id`と`bin`名の対応をどうするかですが、ユーザーの既存の環境の互換性を考えると単純に`<bin> = <contest-id>-<problem-id>`等と仮定するよりはリネームするタイミング(`new`時)でしっかりとメモするのが良いと思います。 Cargo.tomlには[`package.metadata`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table)といううってつけのフィールドがあります。

この考えの下で以下の方法を提案したいと思います。 どうでしょうか?

1. `cargo atcoder new`時に`bin`の名前は`<contest-id>-<problem-id>`と、**ファイル名は従来のまま`<problem-id>.rs`とする**。その際`package.metadata`に`problem-id` → `bin`の対応をメモする。

2. `cargo atcoder new`時に既存のworkspace下に追加されるなら、(`cargo new`する前に)そのworkspaceの`members`に追加する。 **そうでないなら、従来通り1パッケージからなるworkspaceを新たに作り、そこに`profile.release`を書く**。

3. `cargo atcoder new`以外のコマンドでは、1.でメモした表があるならそれで`problem-id` → `bin`を得る。 **そうでないなら、従来通り`problem_id` = `bin`とする**。

```toml
# <workspace-root>/Cargo.toml

[workspace]
members = ["./abc126"]

# packageの方ではなくこちらに書く
[profile.release]
lto = true
panic = 'abort'
```

```toml
# <workspace-root>/abc126/Cargo.toml

[package]
name = "abc126"
version = "0.1.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"

[package.metadata.cargo-atcoder.problems]
a = { bin = "abc126-a" }
b = { bin = "abc126-b" }
c = { bin = "abc126-c" }
d = { bin = "abc126-d" }
e = { bin = "abc126-e" }
f = { bin = "abc126-f" }

[[bin]]
name = "abc126-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc126-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc126-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc126-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc126-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc126-f"
path = "./src/bin/f.rs"

# こっちではなくroot manifestに書く
#[profile.release]
#lto = true
#panic = 'abort'

[dependencies]
proconio = { version = "0.4.1", features = ["derive"] }
```

(edit) 互換性を保とうとする理由ですが、Codeforces等にも参加している人なんかは`std`しか使わないのでこの機能による恩恵がほぼゼロに等しく、そういう人にとっては煩わしさの方が勝ると思われるからです。 実際[Rustの提出をスクレイピング](https://gist.github.com/qryxip/d154944658df7d31e926993d675378a3)してみると、2020年環境であっても`proconio`を含めクレートを使用している人はあまり多くはありません。

![submissions](https://user-images.githubusercontent.com/14125495/81972387-778bd880-965d-11ea-9d6a-bbbf210b2ab7.png)
