### ISSUE TITLE
Save test cases in files

### ISSUE THREAD

**Issue by qryxip** [tanakh/cargo-atcoder#38]
ファイルに保存して閲覧、編集できたほうが便利だと思うので。 方針としては以下の2つがあります。

## ディレクトリにテキストを入れる

`tests/in/test1.txt`と`tests/out/test1.txt`、あるいは`tests/test1.in`と`tests/test2.in`をペアにするような保存形式です。

[oj](https://github.com/online-judge-tools/oj)(とそれに依存する[atcoder-cli](https://github.com/Tatamo/atcoder-cli)等のツール)をはじめとしたほぼすべての競プロツールがこれのはずです。

#### Pros

- 我々の実装が非常に楽
- その場のシェルスクリプトで簡単にテストケースを追加できる
- 外部から読みやすい
- MiB級のサイズのデータに追加の対応が要らない

#### Cons

- 一覧するのが面倒
- 直に書き込むのにファイルを2つ開く必要がある

## JSONやYAMLで管理

[competitive-companion](https://github.com/jmerle/competitive-companion)とかがこれです。あと[私が作ったの](https://github.com/qryxip/snowchains)も。

一応、大きいデータに対応するため一部をテキストファイルに替えることができます。

私のツールだとこんなのです。

```yaml
---
type: batch       # "batch", "interactive", or "unsubmittable"
timelimit: 2000ms # optional
match: exact      # "any", "exact", or "float"

cases:
  - name: Sample 1
    in: |
      1
      2 3
      test
    out: |
      6 test
  - name: Sample 2
    in: |
      72
      128 256
      myonmyon
    out: |
      456 myonmyon
  # "name" and "out" are optional
  - in: |
      1000
      1000 1000
      oooooooooooooo
```

#### Pros

- 上記のConsの逆
- コンテスト開始時にRustのソースファイルと共にエディタで開くといったことが可能

#### Cons

- 上記のProsの逆
